remote_theme: mmistakes/minimal-mistakes
title: "Palaeography"
description: "Image gallery for manuscript studies"
baseurl: "/palaeography"
url: "https://sjabrookes.github.io"

include:
  - _pages

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Site Author
author:
  name: "Stewart J. Brookes"

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
