remote_theme: mmistakes/minimal-mistakes
title: ""
description: "Image gallery for Palaeography: An Introduction"
logo: "/assets/images/home_icon.png"
baseurl: "/palaeography"
url: "https://sjabrookes.github.io"

include:
  - _pages

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Site Author
author:
  name: "Stewart J. Brookes"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "scripts"
